

class WordConnection:
    def __init__(self,name,connection):
        self.name = name
        self.connection = connection
        
    def __str__(self):
        return f"WordConnection(name={self.name}, connection={self.connection})"
    
#    WordConnection("", ["", "", ""]),
wc = [

WordConnection("People", ["Watch"]),
WordConnection("Watch", ["Dog", "Out"]),
WordConnection("Under", ["Dog", "Over", "Line", "Stand", "Wear"]),
WordConnection("Out", ["Side", "House", "Going"]),
WordConnection("Dog", ["House", "Walk", "Years"]),
WordConnection("Side", ["Job", "Door", "Back", "Dance", "Talk", "Meeting"]),
WordConnection("Job", ["Application", "Fair", ""]),
WordConnection("Fair", ["Game", "", ""]),
WordConnection("Game", ["Over", "Time", ""]),
WordConnection("Over", ["Time", "Going", "Watch", "Out", "Under", ""]),
WordConnection("Going", ["Away", "Home", ""]),
WordConnection("Walk", ["Away", "Home", ""]),
WordConnection("Away", ["Team", "", ""]),
WordConnection("Team", ["Player", "Plan", ""]),
WordConnection("First", ["Player", "Time", "Game", "Watch", "House", "Dance", "Down", "Light"]),
WordConnection("Player", ["Out", "Handle", ""]),
WordConnection("Home", ["Coming", "Alone", "Store"]),
WordConnection("Store", ["Door", "Line", ""]),
WordConnection("Alone", ["Time", "", ""]),
WordConnection("Time", ["Out", "Away", ""]),
WordConnection("Coming", ["Back", "Over", ""]),
WordConnection("Back", ["Door", "Side", "Talk", "Line", "Road", "Off"]),
WordConnection("Talk", ["Show", "", ""]),
WordConnection("Show", ["Room", "Time", ""]),
WordConnection("Storage", ["Room", "", ""]),
WordConnection("Room", ["Tour", "", ""]),
WordConnection("Tour", ["Job", "", ""]),
WordConnection("Door", ["Handle", "", ""]),
WordConnection("Handle", ["Bar", "Well", ""]),
WordConnection("Well", ["Done", "", ""]),
WordConnection("Done", ["Over", "", ""]),
WordConnection("Bar", ["Stool", "Food", ""]),
WordConnection("Food", ["Bank", "Storage", ""]),
WordConnection("Bank", ["Watch", "Line", ""]),
WordConnection("Stool", ["Sit", "", ""]),
WordConnection("Sit", ["Down", "Alone", "Back"]),
WordConnection("Years", ["Away", "Gone", ""]),
WordConnection("Gone", ["Home", "Away", "Fishing"]),
WordConnection("House", ["Show", "Tour", "Party", "Cleaner", "Rug", "Cat"]),
WordConnection("Fishing", ["Pole", "Line", ""]),
WordConnection("Line", ["Dance", ""]),
WordConnection("Pole", ["Dance", "", ""]),
WordConnection("Dance", ["Off", "Time", "Show", "Song"]),
WordConnection("Off", ["Side", "Putting", ""]),
WordConnection("Moon", ["Light", "", ""]),
WordConnection("Light", ["Side", "Weight", "Bulb", "Year"]),
WordConnection("Weight", ["Loss", "", ""]),
WordConnection("Honey", ["Moon", "", ""]),
WordConnection("Loss", ["Time", "", ""]),
WordConnection("Full", ["Moon", "Time", "Team"]),
WordConnection("New", ["House", "Year", "Moon"]),
WordConnection("Year", ["Book", "", ""]),
WordConnection("Book", ["Club", "Worm", ""]),
WordConnection("Club", ["House", "Meeting", ""]),
WordConnection("Meeting", ["Time", "", ""]),
WordConnection("Worm", ["Hole", "", ""]),
WordConnection("Hole", ["Dig", "", ""]),
WordConnection("Dig", ["Down", "Under", ""]),
WordConnection("Down", ["Town", "Time", ""]),
WordConnection("Stand", ["Proud", "", ""]),
WordConnection("Proud", ["Parent", "Heart", "Soul"]),
WordConnection("Town", ["House", "Store", "Hall"]),
WordConnection("Parent", ["Meeting", "", ""]),
WordConnection("Bitter", ["Sweet", "", ""]),
WordConnection("Sweet", ["Heart", "", ""]),
WordConnection("Heart", ["Attack", "", ""]),
WordConnection("Attack", ["Plan", "", ""]),
WordConnection("Plan", ["Well", "", ""]),
WordConnection("Bulb", ["Plant", "", ""]),
WordConnection("Plant", ["Life", "", ""]),
WordConnection("Life", ["Plan", "Guard", ""]),
WordConnection("Guard", ["Rail", "", ""]),
WordConnection("Rail", ["Road", "", ""]),
WordConnection("Road", ["Side", "Music", ""]),
WordConnection("Soul", ["Music", "Food", ""]),
WordConnection("Music", ["Theory", "Note", ""]),
WordConnection("Sticky", ["Note", "Fingers", ""]),
WordConnection("Fingers", ["Hole", "", ""]),
WordConnection("Note", ["Take", "Sheet", ""]),
WordConnection("Theory", ["Talk", "", ""]),
WordConnection("Take", ["Off", "Down", "Away"]),
WordConnection("Putting", ["Away", "Down", ""]),
WordConnection("Party", ["Game", "Animal", ""]),
WordConnection("Animal", ["Cracker", "", ""]),
WordConnection("Cracker", ["Jack", "", ""]),
WordConnection("Jack", ["Ass", "Hammer", ""]),
WordConnection("Hammer", ["Time", "Head", ""]),
WordConnection("Head", ["Ass", "Wear", ""]),
WordConnection("Wear", ["Down", "", ""]),
WordConnection("Ass", ["Hole", "", ""]),
WordConnection("Slime", ["Ball", "", ""]),
WordConnection("Ball", ["Pit", "Game", ""]),
WordConnection("Pit", ["Bull", "Fall", ""]),
WordConnection("Fall", ["Down", "Over", ""]),
WordConnection("Bull", ["Worm", "Shark", ""]),
WordConnection("Shark", ["Tank", "", ""]),
WordConnection("Tank", ["Top", "", ""]),
WordConnection("Top", ["Hat", "Down", ""]),
WordConnection("Hat", ["Store", "", ""]),
WordConnection("Navy", ["Blue", "Base", ""]),
WordConnection("Base", ["Ball", "Game", ""]),
WordConnection("Blue", ["Ball", "Slime", "House"]),
WordConnection("Knee", ["Deep", "", ""]),
WordConnection("Deep", ["Hole", "Down", "Sleep"]),
WordConnection("Sleep", ["Tight", "", ""]),
WordConnection("Tight", ["End", "Ass", ""]),
WordConnection("End", ["Game", "Portal", ""]),
WordConnection("Portal", ["Gun", "", ""]),
WordConnection("Gun", ["Show", "", ""]),
WordConnection("Stick", ["Man", "Figure", ""]),
WordConnection("Man", ["Down", "", ""]),
WordConnection("Hall", ["Way", "", ""]),
WordConnection("Way", ["Gone", "", ""]),
WordConnection("Figure", ["Out", "", ""]),
WordConnection("Throw", ["Rug", "Down", ""]),
WordConnection("Rug", ["Burn", "", ""]),
WordConnection("Burn", ["Cream", "Out", ""]),
WordConnection("Cream", ["Cheese", "", ""]),
WordConnection("Cheese", ["Pizza", "", ""]),
WordConnection("Pizza", ["Oven", "", ""]),
WordConnection("Toaster", ["Oven", "", ""]),
WordConnection("Oven", ["Cleaner", "", ""]),
WordConnection("Cleaner", ["Supplies", "", ""]),
WordConnection("Supplies", ["Store", "", ""]),
WordConnection("Baby", ["Face", "", ""]),
WordConnection("Face", ["Off", "Time", ""]),
WordConnection("Cat", ["Fight", "Walk", ""]),
WordConnection("Fight", ["Song", "Plan", ""]),
WordConnection("Song", ["Lyric", "", ""]),
WordConnection("Lyric", ["Sheet", "", ""]),
WordConnection("Hard", ["Take", "Hat", ""]),
WordConnection("Sheet", ["Metal", "", ""]),
WordConnection("Cookie", ["Sheet", "", ""]),
WordConnection("Metal", ["Rock", "Band", ""]),
WordConnection("Rock", ["Music", "", ""]),
WordConnection("Band", ["Practice", "", ""]),
WordConnection("Practice", ["Time", "", ""]),
WordConnection("Garage", ["Band", "", ""]),
          ]